# This file is part of rinohtype, the Python document preparation system.
#
# Copyright (c) Brecht Machiels.
#
# Use of this source code is subject to the terms of the GNU Affero General
# Public License v3. See the LICENSE file or http://www.gnu.org/licenses/.


PLATFORM_UNICODE = 0
PLATFORM_MACINTOSH = 1
PLATFORM_ISO = 2
PLATFORM_WINDOWS = 3
PLATFORM_CUSTOM = 4

LANGUAGE_WINDOWS_EN_US = 0x0409

NAME_COPYRIGHT = 0
NAME_FAMILY = 1
NAME_SUBFAMILY = 2
NAME_UID = 3
NAME_FULL = 4
NAME_VERSION = 5
NAME_PS_NAME = 6
NAME_TRADEMARK = 7
NAME_MANUFACTURER = 8
NAME_DESIGNER = 9
NAME_DESCRIPTION = 10
NAME_VENDOR_URL = 11
NAME_DESIGNER_URL = 12
NAME_LICENSE = 13
NAME_LICENSE_URL = 14
NAME_TYPOGRAPHIC_FAMILY = 16
NAME_TYPOGRAPHIC_SUBFAMILY = 17
# ...
NAME_WWS_FAMILY = 21
NAME_WWS_SUBFAMILY = 22
# ...

UNICODE_1_0 = 0
UNICODE_1_1 = 1
UNICODE_ISO_IEC_10646 = 2
UNICODE_2_0_BMP = 3
UNICODE_2_0_FULL = 4
UNICODE_VAR_SEQ = 5
UNICODE_FULL = 6

ISO_ASCII = 0
ISO_10646 = 1
ISO_8859_1 = 2
