name: "Crash report"
description: "rinohtype fails to produce a valid PDF file"
labels: ["bug", "crash"]
body:
  - type: markdown
    attributes:
      value: >
        Thanks for taking the time to fill out this bug report! ❤️
        
        
        Sometimes bugs have already been fixed in the master branch. Please try to
        reproduce the crash with the current master version of rinohtype before you
        file a bug report. You can install it directly from GitHub:

            pip install https://github.com/brechtm/rinohtype/archive/refs/heads/master.zip

        Please provide the following information to make your bug report as useful as
        possible.
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search the issues to see if an issue already exists
                   for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: true
  - type: textarea
    id: messages
    attributes:
      label: Sphinx or rinoh output
      description: The messages output by rinohtype (and Sphinx) when rendering
                   the document.
      render: text
    validations:
      required: true
  - type: textarea
    id: source
    attributes:
      label: Source files
      description: The Sphinx project files or inputs to rinoh that cause the crash.
                   These are crucial for reproducing the issue! Issues with source
                   files attached get priority. Please also provide any additional
                   information that could be useful.
      placeholder: |
        - insert a link to the input files (e.g. a Sphinx project repository), or
        - attach an archive (e.g. zip) containing the source files

        If you cannot share the source files publicly, try to create dummy input
        files that reproduce the bug (this may be difficult). Alternatively, you can
        send the input files to me privately at brecht@opqode.com (I will not share
        them with others, of course).
    validations:
      required: true
  - type: textarea
    id: versions
    attributes:
      label: Versions
      description: Version information for rinohtype, Sphinx, Python and your operating system
      placeholder: |
        Paste the output of `rinoh --versions` (trailing _s_!), for rinohtype >= 0.5.4

        Otherwise, the output of:
          rinoh --version
          sphinx-build --version
          python --version
          python -c "import platform; print(platform.platform())"
      render: text
    validations:
      required: true
