name: Experiment

on: [push]

env:
  poetry_version: '1.1.4'
jobs:
  unit-tests:
    name: ${{ matrix.os }} / ${{ matrix.python-version }} unit tests
    strategy:
      fail-fast: false
      matrix:
        os: [Ubuntu, macOS, Windows]
        python-version: [3.6, 3.10.0-alpha - 3.10, pypy-3.7]
    runs-on: ${{ matrix.os }}-latest
    steps:
    - name: Install Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install tox & co
      run: |
        pip3.9 install --requirement .github/workflows/requirements.txt
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install Python ${{ matrix.python-version }}
      if: matrix.python-version != '3.9'
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set TOXENV matching Python ${{ matrix.python-version }}
      uses: jannekem/run-python-script-action@v1
      with:
        script: |
          import os
          mapping = {'3.6':                 'py36',
                     '3.7':                 'py37',
                     '3.8':                 'py38',
                     '3.9':                 'py39',
                     '3.10.0-alpha - 3.10': 'py310',
                     'pypy-3.6':            'pypy3',
                     'pypy-3.7':            'pypy3'}
          toxenv = mapping['${{ matrix.python-version }}']
          with open(os.getenv('GITHUB_ENV'), 'a') as env:
              print(f'TOXENV={toxenv}', file=env)
    - name: Run tox
      run: |
        tox -v
